# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'UI: npm install'
  workingDirectory: photo-library-ui

- script: |
    npm run build
  displayName: 'UI: npm build'
  workingDirectory: photo-library-ui

- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: photo-library

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/photo-library'
    contents: |
        */*        
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'

